
default: &default
  adapter: postgresql
  encoding: unicode
  database: myaouth
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
